[project]
name = "llm-training-exercises"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "marimo==0.25.1",
    "tiktoken==0.14.0",
]

[tool.marimo.runtime]
auto_instantiate = true
on_cell_change = "autorun"

[tool.marimo.display]
theme = "light"

[tool.marimo.ai]
enabled = false

[dependency-groups]
prompting = ["transformers==4.57.1", "torch==2.8.0"]
rag = [{include-group = "prompting"}, "chromadb==1.5.9"]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cpu" }
